#!/usr/bin/env tsx
/**
 * Script interativo para configurar variáveis de ambiente WhatsApp.
 * Gera ou atualiza .env.local preservando linhas existentes não relacionadas.
function parseArgs() {
  const args = process.argv.slice(2)
  const opts: Record<string, string | boolean> = {}
  for (const a of args) {
    if (a === '--non-interactive') opts.nonInteractive = true
    else if (a.startsWith('--')) {
      const [k, v] = a.replace(/^--/, '').split('=')
      if (k) opts[k] = v ?? ''
    }
  }
  return opts
}

 *
 * Uso:
 *   pnpm setup:whatsapp
 *   pnpm setup:whatsapp --test +5511999998888
 */

import fs from 'fs'
import path from 'path'
import readline from 'readline'

interface Answers {
  provider: string
  phoneNumberId?: string
  apiUrl?: string
  token: string
  pix: string
  appUrl: string
  automatic: string
  testPhone?: string
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})
const ask = (q: string) =>
  new Promise<string>((res) => rl.question(q, (ans) => res(ans.trim())))

async function main() {
  console.log('\n⚙️  Configuração WhatsApp - Assistente Rápido')
  console.log('---------------------------------------------')
  const provider =
    (await ask('Provider (meta/twilio/generic/zapi) [meta]: ')) || 'meta'

  let phoneNumberId: string | undefined
  let apiUrl: string | undefined

  if (provider === 'meta') {
    phoneNumberId = await ask('Meta PHONE_NUMBER_ID (ex 123456789012345): ')
  } else if (provider === 'generic') {
    apiUrl = await ask(
      'Gateway API URL (ex http://localhost:3000/api/whatsapp/fake-gateway): '
    )
  } else if (provider === 'twilio') {
    apiUrl = await ask(
      'Twilio proxy URL (ex http://localhost:3000/api/whatsapp/twilio-proxy): '
    )
  } else if (provider === 'zapi') {
    apiUrl = await ask(
      'Z-API URL (ex https://api.z-api.io/instances/.../send-text): '
    )
  }

  const token = await ask('API Token (Meta token / gateway key / fake): ')
  const pix = await ask('PIX Key (email/EVP/etc): ')
  const appUrl =
    (await ask('APP_URL [http://localhost:3000]: ')) || 'http://localhost:3000'
  const automatic =
    (await ask('Enviar automático completo? (true/false) [false]: ')) || 'false'
  const testPhone = await ask(
    'Número teste E.164 (+5511999998888) (opcional): '
  )

  const answers: Answers = {
    provider,
    phoneNumberId,
    apiUrl,
    token,
    pix,
    appUrl,
    automatic,
    testPhone,
  }

  const envPath = path.join(process.cwd(), '.env.local')
  let existing = ''
  if (fs.existsSync(envPath)) existing = fs.readFileSync(envPath, 'utf8')

  const lines = existing.split(/\r?\n/)
  const keep: string[] = []
  for (const line of lines) {
    if (!line.trim()) {
      keep.push(line)
      continue
    }
    if (
      /^WHATSAPP_/i.test(line) ||
      /^PIX_KEY=/i.test(line) ||
      /^APP_URL=/i.test(line) ||
      /^TEST_PHONE=/i.test(line)
    ) {
      // skip old whatsapp related lines
      continue
    }
    keep.push(line)
  }

  const newBlock: string[] = []
  newBlock.push(
    '# ==== WhatsApp Configuration (generated by setup-whatsapp.ts) ===='
  )
  newBlock.push(`WHATSAPP_PROVIDER=${answers.provider}`)
  if (answers.phoneNumberId)
    newBlock.push(`WHATSAPP_PHONE_NUMBER_ID=${answers.phoneNumberId}`)
  if (answers.apiUrl) newBlock.push(`WHATSAPP_API_URL=${answers.apiUrl}`)
  newBlock.push(`WHATSAPP_API_TOKEN=${answers.token}`)
  newBlock.push(`PIX_KEY=${answers.pix}`)
  newBlock.push(`APP_URL=${answers.appUrl}`)
  newBlock.push(`WHATSAPP_SEND_AUTOMATIC=${answers.automatic}`)
  if (answers.testPhone) newBlock.push(`TEST_PHONE=${answers.testPhone}`)
  newBlock.push(
    '# ==============================================================='
  )

  const finalContent = [...keep, '', ...newBlock, ''].join('\n')
  fs.writeFileSync(envPath, finalContent, 'utf8')
  console.log(`\n✅ Arquivo atualizado: ${envPath}`)

  if (answers.testPhone) {
    console.log('\n📨 Enviando mensagem de teste...')
    process.env.WHATSAPP_PROVIDER = answers.provider
    if (answers.phoneNumberId)
      process.env.WHATSAPP_PHONE_NUMBER_ID = answers.phoneNumberId
    if (answers.apiUrl) process.env.WHATSAPP_API_URL = answers.apiUrl
    process.env.WHATSAPP_API_TOKEN = answers.token
    process.env.PIX_KEY = answers.pix
    process.env.APP_URL = answers.appUrl
    process.env.WHATSAPP_SEND_AUTOMATIC = answers.automatic
    process.env.TEST_PHONE = answers.testPhone
    const { WhatsAppService } = await import(
      '../src/services/notifications/WhatsAppService'
    )
    const result = await WhatsAppService.send({
      to: answers.testPhone,
      body: 'Teste rápido ✅ Se chegou, integração OK.',
    })
    console.log('Resultado:', result)
  }

  rl.close()
}

main().catch((err) => {
  console.error('❌ Erro:', err)
  rl.close()
  process.exit(1)
})
